-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [estimate_size_aeneas]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace EstimateSizeAeneas

/-- [estimate_size_aeneas::estimate_size_panic]:
    Source: 'src/../../../../src/estimate_size.rs', lines 1:0-21:1 -/
def estimate_size_panic (x : Std.U32) : Result Std.U32 := do
  massert ((x < 256#u32) || ((¬ (x < 1024#u32)) || (¬ (x > 1022#u32))))
  if x < 256#u32
  then if x < 128#u32
       then ok 1#u32
       else ok 3#u32
  else
    if x < 1024#u32
    then ok 5#u32
    else if x < 2048#u32
         then ok 7#u32
         else ok 9#u32

/-- [estimate_size_aeneas::estimate_size_correction]:
    Source: 'src/../../../../src/estimate_size.rs', lines 23:0-43:1 -/
def estimate_size_correction (x : Std.U32) : Result Std.U32 := do
  if x < 256#u32
  then if x < 128#u32
       then ok 1#u32
       else ok 3#u32
  else
    if x < 1024#u32
    then if x > 1022#u32
         then ok 4#u32
         else ok 5#u32
    else if x < 2048#u32
         then ok 7#u32
         else ok 9#u32

end EstimateSizeAeneas
